[package]
name = "jocky-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
serde.workspace = true
serde_json.workspace = true
jocky-ast = { path = "../jocky-ast" }
jocky-parser = { path = "../jocky-parser" }
jocky-common = { path = "../jocky-common" }
sysinfo = "0.39"
sha2 = "0.10"
chrono = "0.4"
